    For this part of the project I chose to examine numpy libraries and a specfic function within said library. This function is np.linalg.eig(b). np.linalg.eig(b) computes the eigen values and vectors of a 2d array b. b must be a square 2D array (meaning the rows equal the columns) so that we an commute this and if it is not a sqaure array you will get an error. If the eigenvalue math does not converge then we should use np.linalg.LinAlgError(b) however, in our final project we did not need this. Now the function will return two different 1D arrays one for the eigenvalues and one for the eigenvectors. Looking first a the 1D array for eigenvalues the a not necessarily order and the the array can be complex with both the imaginary and real part. Then the eigenfunction array will be the normalized eigenvetors and the eigenvector placement should correspond with the eigenvalue associated with it. For example eigenvectors[:,i] will go with eigenvalues[i]. You should use this when you need eigenvalues and vectors as matrix multpication in python (or on paper) can get difficult. Below is an example of how this can be implemented.

In [9]:
import numpy as np

b = np.array([[-3, 4, 0, 7],
             [3, 6, 2, 0],
             [0, 1, 9, 1],
             [9, 0, 8, -2]])

print()
print(np.linalg.eig(b))
print()


EigResult(eigenvalues=array([-11.06259997,   3.41481398,  11.08616534,   6.56162064]), eigenvectors=array([[ 0.68455782, -0.46633648,  0.42661705, -0.40412335],
       [-0.12528145,  0.51238614,  0.44978516, -0.83185471],
       [ 0.0419769 ,  0.03719798,  0.50391526,  0.37259164],
       [-0.71688429, -0.72014376,  0.60146539, -0.07666505]]))



    Now for the final project we used this function for the k matrix where the k matrix is the matrix of all of the spring constants ordered aas they were in the system of first order ODEs. for the first part of the project it look like below ...


In [11]:
print()

k = 1
K = np.array([[-2*k, k, 0, k],
             [k, -2*k, k, 0],
             [0, k, -2*k, k],
             [k, 0, k, -2*k]])

eVal, eVec = np.linalg.eig(K)

for i in range(len(eVal)):
    print("For mass", i+1, "the eigen value is", round(eVal[i],1), "with the eigenstate being ")
    print()
    print(eVec[i])
    print()


For mass 1 the eigen value is 0.0 with the eigenstate being 

[-5.00000000e-01 -7.07106781e-01 -5.00000000e-01  5.55111512e-17]

For mass 2 the eigen value is -2.0 with the eigenstate being 

[-5.00000000e-01  2.74466000e-16  5.00000000e-01 -7.07106781e-01]

For mass 3 the eigen value is -4.0 with the eigenstate being 

[-5.00000000e-01  7.07106781e-01 -5.00000000e-01  2.58507341e-16]

For mass 4 the eigen value is -2.0 with the eigenstate being 

[-5.00000000e-01 -3.08103393e-17  5.00000000e-01  7.07106781e-01]



    We used this for a couple parts of our final project. The first part was to ckeck both our math and graph as we knew from perodic systems we could check the expected eigenvalues to the ones we got. Then once we chacked that we compared it to the graph to compare the symmetries between mass 2 and mass 4. Then we used it for the n -matrix seeing if the symmetry is consistent with the eigen values and if that matched up with the corresponding graphs. We ultimetly did find a correlation between the two. 